[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.9.0",
    "fastapi>=0.103.0",
    "python-dotenv==1.1.0",
    "chainlit==2.8.0",
    "gradio==5.33.1",
]

